-- root 用户
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_user` (`id`, `renter_id`, `dept_id`, `username`, `real_name`, `sex`, `age`, `email`, `card_id`, `phone`, `pswd`, `create_time`, `last_login_time`, `status`, `login_token`, `out_date`, `last_updated_date`, `q_one`, `q_two`, `q_three`, `a_one`, `a_two`, `a_three`, `validate_code`, `visit_times`) VALUES ('1', NULL, '1', 'root', 'root', '2', '25', '8412130272@qq.com', '366534653979347682', '13623215682', '7ee86ea7ca89728ef5f08aa0aef7a120', '2016-06-16 11:15:33', '2018-12-03 15:35:21', '1', '1adc4493320f46d7b25fb6cb1780603e=root', '2017-08-10 19:39:14', '2018-07-19 14:52:23', NULL, NULL, NULL, NULL, NULL, NULL, '03c361d5-c76e-4467-bf90-aec2df4429cb', '1434');


-- root 角色
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role` (`id`, `renter_id`, `code`, `name`, `type`, `is_active`, `remark`, `create_time`, `last_update_time`) VALUES ('1', NULL, 'super_admin', '超级管理员', '888888', '1', NULL, NULL, NULL);



-- 用户角色关联数据
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_user_role` (`uid`, `rid`) VALUES ('1', '1');



INSERT INTO `idatrix_unisecurity_role_sys` VALUES ('1', 'security');


-- 系统
INSERT INTO `idatrix_unisecurity_client_system` VALUES ('catalog', 'catalog', 'http://10.0.0.83:60040/servicebase', '/index.shtml', 'http://127.0.0.1:8082');
INSERT INTO `idatrix_unisecurity_client_system` VALUES ('cloudetl', 'cloudetl', 'http://10.0.0.84:60090/cloudetl', '/index.shtml', 'http://127.0.0.1:8085');
INSERT INTO `idatrix_unisecurity_client_system` VALUES ('datalab', 'datalab', 'http://10.0.0.85:60060/datalab/', '/index.shtml', 'http://127.0.0.1:8084');
INSERT INTO `idatrix_unisecurity_client_system` VALUES ('dataResDir', 'dataResDir', 'http://10.0.0.85:60070/idatrix-metacube-web', '/index.shtml', 'http://127.0.0.1:8087');
INSERT INTO `idatrix_unisecurity_client_system` VALUES ('idatrix-metacube-web', 'idatrix-metacube-web', 'http://10.0.0.85:60070/metacube', '/index.shtml', 'http://127.0.0.1:8081');
INSERT INTO `idatrix_unisecurity_client_system` VALUES ('ITIL', 'ITIL', 'http://10.0.0.83:8080/#/main/dashboard/metrics', '/index.shtml', 'http://127.0.0.1:8086');
INSERT INTO `idatrix_unisecurity_client_system` VALUES ('monitor', 'monitor', 'http://10.0.0.83:8080/#/main/alerts', '/index.shtml', 'http://127.0.0.1:8088');
INSERT INTO `idatrix_unisecurity_client_system` VALUES ('security', 'security', 'http://10.0.0.83:60020/security', '/index.shtml', 'http://127.0.0.1:8083');
INSERT INTO `idatrix_unisecurity_client_system` VALUES ('servicebase', 'servicebase', 'http://10.0.0.85:60040/servicebase-web', '/index.shtml', 'http://127.0.0.1:8082');



-- 权限
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1', null, '', '', '子系统1', '1', '1', '', null);
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2', '22', '按钮', '/renter/add.shtml', '租户新建', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('3', '22', '按钮', '/renter/update.shtml', '租户修改', '1', '2', null, 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('4', '22', '按钮', '/renter/delete.shtml', '租户删除', '1', '3', null, 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('5', '26', '菜单', '/permission/list.shtml', '资源管理', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('6', '5', '按钮', '/permission/add.shtml', '资源新增', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('7', '5', '按钮', '/permission/deletePermissionById.shtml', '资源删除', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('8', '26', '菜单', '/member/users.shtml', '用户管理', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('12', '8', '按钮', '/member/delete.shtml', '用户删除', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('14', '18', '按钮', '/permission/addPermission2Role.shtml', '角色授权', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('16', '18', '按钮', '/role/deleteRoleById.shtml', '角色删除', '1', '1', null, 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('17', '18', '按钮', '/role/add.shtml', '角色添加', '1', '1', null, 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('18', '26', '菜单', '/role/list.shtml', '角色管理', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('20', '18', '按钮', '/role/addUserToRole', '角色添加用户', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('21', '8', '按钮', '/member/add.shtml', '用户新建', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('22', '26', '菜单', '/renter/list.shtml', '租户管理', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('23', '1', '系统', null, '数据采集&集成', '1', '1', null, 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('24', '1', '系统', null, '数据分析&探索', '1', '1', null, 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('25', '1', '系统', null, '服务开放&治理', '1', '1', null, 'servicebase');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('26', '1', '系统', null, '安全管理', '1', '1', null, 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('27', '1', '系统', '', '大数据应用开发环境', '1', '1', '', 'ITIL');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('28', '1', '系统', '', '数据共享交换平台', '1', '1', '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('29', '1', '系统', null, '元数据管理', '1', '1', null, 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('30', '1', '系统', null, '运维监控', '1', '1', null, 'monitor');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('32', '26', '菜单', '/organization/list.shtml', '组织机构管理', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('33', '32', '按钮', '/organization/add.shtml', '组织添加', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('34', '32', '按钮', '/organization/update.shtml', '组织修改', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('35', '32', '按钮', '/organization/delete.shtml', '组织删除', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('37', '8', '按钮', '/member/update.shtml', '用户修改', '1', '1', null, 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('40', '18', '按钮', '/role/update.shtml', '角色修改', '1', '1', null, 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('42', '32', '按钮', '/organization/export.shtml', '组织导出', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('43', '32', '按钮', '/organization/import.shtml', '组织导人', '1', '1', '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('44', '8', '按钮', '/member/export.shtml', '用户导出', '1', '1', null, 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('45', '8', '按钮', '/member/import.shtml', '用户导入', '1', '1', null, 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('46', '32', '按钮', '/organization/addUserToOrg.shtml', '用户添加到组织', '1', '1', null, 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('61', '24', '菜单', '/db/storage/list', '数据查询', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('71', '24', '菜单', '/hdfs/metadata/list', '目录管理', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('81', '24', '菜单', '/task/definition/getTasks', '任务管理', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('91', '61', '按钮', '/db/sql/execute', '执行', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('101', '61', '按钮', '/db/sql/history', '执行历史', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('171', '25', '菜单', '/app/list', '我的应用', '1', null, '', 'servicebase');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('181', '25', '菜单', '/service/list', '数据访问API', '1', null, '', 'servicebase');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('191', '181', '按钮', '/service/detail', 'API详情', '1', null, '', 'servicebase');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('201', '171', '按钮', '/app/add', '新建', '1', null, '', 'servicebase');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('211', '171', '按钮', '/app/update', '修改', '1', null, '', 'servicebase');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('221', '171', '按钮', '/app/delete', '删除', '1', null, '', 'servicebase');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('361', '351', '按钮', 'http://111.111.111.111', '新建监控', '1', null, '', 'monitor');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('371', '351', '按钮', 'http://2.2.2.2', '修改监控', '1', null, '', 'monitor');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('381', '81', '按钮', '/task/definition/createTask', '新增任务', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('401', '81', '按钮', '/task/definition/updateTaskAndFlow', '保存任务信息', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('411', '81', '按钮', '/task/definition/deleteTask', '删除任务', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('421', '81', '按钮', '/executor/startTask', '执行任务', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('431', '81', '按钮', '/executor/createTaskSchedule', '创建调度', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('441', '81', '按钮', '/executor/pauseTask', '暂停执行', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('451', '81', '按钮', '/executor/cancelTask', '停止执行', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('461', '81', '按钮', '/executor/resumeTask', '恢复执行', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('501', '81', '按钮', '/executor/statTask', '任务统计', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('511', '81', '按钮', '/executor/getTaskNodeInfo', '任务节点当前执行状态', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('521', '81', '按钮', '/executor/getTaskExecLog', '单个历史任务日志', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('531', '81', '按钮', '/executor/getNodeExecLog', '节点详情', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('541', '81', '按钮', '/task/definition/upload', '上传Jar包', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('551', '81', '按钮', '/task/definition/tasktype/sparksubmit', '创建SparkSubmit任务', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('561', '81', '按钮', '/task/definition/tasktype/hadoopjava', '创建HadoopJava任务', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('571', '81', '按钮', '/task/definition/tasktype/command', '创建Command任务', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('581', '81', '按钮', '/task/definition/tasktype/hivejob', '创建HiveJob任务', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('591', '81', '按钮', '/task/definition/view', '获取任务信息', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('601', '71', '菜单', '/hdfs/file/list', 'HDFS文件目录查询', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('611', '601', '按钮', '/hdfs/file/new', '新建目录', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('621', '601', '按钮', '/hdfs/file/rename', '重命名', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('631', '601', '按钮', '/hdfs/file/upload', '上传文件', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('641', '601', '按钮', '/hdfs/file/download', '下载文件', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('651', '601', '按钮', '/hdfs/file/delete', '删除', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('661', '5', '按钮', '/permission/update.shtml', '资源修改', '1', null, '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('671', '5', '按钮', '/permission/getSystem.shtml', '获取子系统权限', '1', null, '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('681', '5', '按钮', '/permission/getRes.shtml', '获取登录用户的权限', '1', null, '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('691', '5', '按钮', '/permission/user-permits.shtml', '获取用户的权限', '1', null, '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('701', '8', '按钮', '/role/addUsersToRoles.shtml', '分配组织或角色', '1', null, '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('711', '29', '菜单', '/frontEndServerController/get', '资源管理', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('721', '29', '菜单', '/DataSystem', '数据系统注册', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('731', '29', '菜单', '/frontMetadataInfoController', '元数据定义', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('741', '29', '菜单', '/MetaRelationshipController/search', '数据关系管理', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('751', '29', '菜单', '/DataStandardController/search', '数据标准查询', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('901', '23', '菜单', '/cloud/getTransList.do', '转换列表', '1', null, '转换列表', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('911', '23', '菜单', '/cloud/getJobList.do', '调度列表', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('921', '23', '菜单', '/db/getDbList.do', '数据系统', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1001', '901', '按钮', '/trans/newTrans.do', '新建转换', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1031', '911', '按钮', '/job/newJob.do', '新建调度', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1041', '911', '按钮', '/job/deleteJob.do', '删除调度', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1051', '901', '按钮', '/trans/deleteTrans.do', '删除转换', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1061', '23', '菜单', '/cloud/getServerList.do', '服务器', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1071', '23', '菜单', '/cloud/getClusterList.do', '服务器集群', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1081', '23', '菜单', '/cloud/jobtype', '调度组件', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1091', '1081', '按钮', '/cloud/jobtype/SPECIAL', 'START', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1101', '23', '菜单', '/cloud/getHadoopList.do', 'Hadoop集群', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1111', '23', '菜单', '/cloud/getSparkEngineList.do', 'Spark引擎', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1121', '23', '菜单', '/cloud/getDefaultEngineList.do', '执行引擎', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1131', '1081', '按钮', '/cloud/jobtype/DUMMY', 'DUMMY', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1141', '1081', '按钮', '/cloud/jobtype/JOB', '作业', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1151', '1081', '按钮', '/cloud/jobtype/TRANS', '转换', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1161', '1081', '按钮', '/cloud/jobtype/SET_VARIABLES', '设置变量', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1171', '23', '菜单', '/cloud/getFileList.do', '文件模板管理', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1181', '1081', '按钮', '/cloud/jobtype/SUCCESS', '成功', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1191', '1081', '按钮', '/cloud/jobtype/DELAY', '等待', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1201', '1081', '按钮', '/cloud/jobtype/SIMPLE_EVAL', '检验字段的值', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1211', '1081', '按钮', '/cloud/jobtype/SFTP', 'SFTP 下载', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1221', '23', '菜单', '/cloud/transtype', '转换组件', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1231', '1221', '按钮', '/cloud/transtype/TableInput', '表输入', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1241', '1081', '按钮', '/cloud/jobtype/SFTPPUT', 'SFTP 上传', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1251', '1221', '按钮', '/cloud/transtype/TableOutput', '表输出', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1261', '1221', '按钮', '/cloud/transtype/TextFileInput', '文本文件输入', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1271', '1221', '按钮', '/cloud/transtype/TextFileOutput', '文本文件输出', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1281', '1221', '按钮', '/cloud/transtype/AccessInput', 'Access输入', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1301', '1221', '按钮', '/cloud/transtype/CsvInput', 'Csv文件输入', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1311', '1081', '按钮', '/cloud/jobtype/EVAL', '使用 JavaScript 脚本验证', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1321', '1081', '按钮', '/cloud/jobtype/COPY_FILES', 'Copy Files', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1331', '1081', '按钮', '/cloud/jobtype/HadoopCopyFilesPlugin', 'Hadoop Copy Files', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1341', '1221', '按钮', '/cloud/transtype/ExcelInput', 'Excel输入', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1351', '711', '按钮', '/frontEndServerController/insert', '新建', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1361', '711', '按钮', '/frontEndServerController/update', '修改', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1371', '711', '按钮', '/frontEndServerController/updateStatus', '删除', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1401', '721', '菜单', '/dataSourceInfoRegController/search', '前置机 - 数据库', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1411', '721', '菜单', '/ftpUserPathServiceController/get', '前置机 - SFTP用户', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1421', '721', '菜单', '/platformServerInfoController/search', '平台 - 数据库类', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1431', '1401', '按钮', '/dataSourceInfoRegController/insert', '新建', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1441', '1401', '按钮', '/dataSourceInfoRegController/update', '修改', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1451', '1221', '按钮', '/cloud/transtype/GetFileNames', '获取文件名', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1461', '1221', '按钮', '/cloud/transtype/InsertUpdate', '插入/更新', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1471', '1221', '按钮', '/cloud/transtype/ExecSQL', '执行SQL脚本', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1481', '1401', '按钮', '/dataSourceInfoRegController/updateStatus', '删除', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1491', '1221', '按钮', '/cloud/transtype/ScriptValueMod', 'JavaScript代码', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1501', '1401', '按钮', '/frontMetadataInfoController/ds/createMetadata', '创建表', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1511', '1401', '按钮', '/frontMetadataInfoController/createtable', '生成实体表', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1521', '1401', '按钮', '/frontMetadataInfoController/ds/exportMetadata', '导出', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1531', '1221', '按钮', '/cloud/transtype/HadoopFileInputPlugin', 'Hadoop File Input', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1541', '1221', '按钮', '/cloud/transtype/HadoopFileOutputPlugin', 'Hadoop File Output', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1551', '1221', '按钮', '/cloud/transtype/HBaseOutput', 'Hbase Output', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1561', '1221', '按钮', '/cloud/transtype/HBaseInput', 'HBase Input', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1571', '1411', '按钮', '/ftpUserPathServiceController/insert', '新建', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1581', '1411', '按钮', '/ftpUserPathServiceController/update', '修改', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1591', '1221', '按钮', '/cloud/transtype/ConcatFields', 'Concat Fields', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1601', '1221', '按钮', '/cloud/transtype/GetSlaveSequence', 'Get ID from slave se', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1611', '1221', '按钮', '/cloud/transtype/ValueMapper', '值映射', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1621', '1221', '按钮', '/cloud/transtype/SplitFieldToRows3', '列拆分为多行', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1631', '1221', '按钮', '/cloud/transtype/Denormaliser', '列转行', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1641', '1421', '按钮', '/dataSourceInfoRegController/platform/insert', '新建', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1651', '1221', '按钮', '/cloud/transtype/StringCut', '剪切字符串', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1661', '1221', '按钮', '/cloud/transtype/Unique', '去除重复记录', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1671', '1421', '按钮', '/dataSourceInfoRegController/platform/update', '修改', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1681', '1221', '按钮', '/cloud/transtype/UniqueRowsByHashSet', '唯一行 (哈希值)', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1691', '1421', '按钮', '/dataSourceInfoRegController/platform/updateStatus', ' 删除', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1701', '1221', '按钮', '/cloud/transtype/Constant', '增加常量', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1711', '1221', '按钮', '/cloud/transtype/Sequence', '增加序列', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1721', '1221', '按钮', '/cloud/transtype/CheckSum', '增加校验列', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1731', '1221', '按钮', '/cloud/transtype/SelectValues', '字段选择', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1741', '1221', '按钮', '/cloud/transtype/StringOperations', '字符串操作', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1751', '1221', '按钮', '/cloud/transtype/ReplaceString', '字符串替换', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1761', '1221', '按钮', '/cloud/transtype/SetValueConstant', '将字段值设置为常量', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1771', '1221', '按钮', '/cloud/transtype/FieldSplitter', '拆分字段', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1781', '1221', '按钮', '/cloud/transtype/SortRows', '排序记录', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1791', '1221', '按钮', '/cloud/transtype/NumberRange', '数值范围', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1801', '1221', '按钮', '/cloud/transtype/FieldsChangeSequence', '根据字段值来改变序列', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1811', '1221', '按钮', '/cloud/transtype/Flattener', '行扁平化', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1821', '1221', '按钮', '/cloud/transtype/Normaliser', '行转列', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1831', '721', '菜单', '/hdfsPathController/search', '平台 - HDFS', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1841', '1221', '按钮', '/cloud/transtype/Calculator', '计算器', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1851', '1221', '按钮', '/cloud/transtype/SetValueField', '设置字段值', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1861', '1221', '按钮', '/cloud/transtype/AddXML', 'AddXML', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1871', '1831', '按钮', '/hdfsPathController/insert', '新建', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1881', '1831', '按钮', '/hdfsPathController/update', '重命名', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1891', '1831', '按钮', '/hdfsPathController/delete', '删除', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1901', '1221', '按钮', '/cloud/transtype/ElasticSearchBulk', '批量加载', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1911', '1221', '按钮', '/cloud/transtype/StreamLookup', '流查询', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1921', '1221', '按钮', '/cloud/transtype/SwitchCase', 'Switch / Case', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1931', '1221', '按钮', '/cloud/transtype/GroupBy', '分组', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1941', '1221', '按钮', '/cloud/transtype/Validator', '数据检验', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1951', '731', '菜单', '/frontMetadataInfoController/search', '数据表类', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1961', '731', '菜单', '/frontMetafileInfoController/search', '文件目录类', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1971', '1951', '按钮', '/frontMetadataInfoController/createMetadata', '新建', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1981', '1951', '按钮', '/frontMetadataInfoController/updateMetadata', '修改', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('1991', '1951', '按钮', '/FileController/uploadExample', '上传样例', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2031', '751', '按钮', '/FileController/upload', '新建上传', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2041', '751', '按钮', '/FileController/download', '文件下载', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2051', '751', '按钮', '/DataStandardController/Delete', '删除', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2061', '1951', '按钮', '/frontMetadataInfoController/exportMetadata', '导出字段', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2071', '1951', '按钮', '/frontHistoryVersionController/getHistoryVersion', '历史版本', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2081', '1951', '按钮', '/frontMetadataInfoController/moveToRecycle', '移入回收站', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2091', '1951', '按钮', '/frontMetadataInfoController/getRecycle', '查看回收站', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2101', '1951', '按钮', '/frontMetadataInfoController/restore', '从回收站还原', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2111', '1951', '按钮', '/frontMetadataInfoController/batchToDelete', '永久删除', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2121', '1951', '按钮', '/frontMetadataInfoController/createEntyTable', '生成实体表', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2131', '1961', '按钮', '/frontMetafileInfoController/batchInsert', '新建', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2141', '1961', '按钮', '/frontMetafileInfoController/importMetafile', '导入', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2151', '1961', '按钮', '/frontMetafileInfoController/exportMetafile', '导出', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2161', '1961', '按钮', '/frontMetafileInfoController/moveToRecycle', '移入回收站', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2171', '1961', '按钮', '/frontMetafileInfoController/getRecycle', '查看回收站', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2181', '741', '按钮', '/MetaRelationshipController/createRelation', '新建', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2191', '741', '按钮', '/MetaRelationshipController/tableAndFiledRelation', '修改', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2201', '741', '按钮', '/MetaRelationshipController/deleteById', '删除', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2281', '1961', '按钮', '/frontMetafileInfoController/batchToRecovery', '从回收站还原', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2291', '1961', '按钮', '/frontMetafileInfoController/batchToDelete', '永久删除', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2301', '1101', '按钮', '/cloud/saveHadoop.do', '新建', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2311', '1101', '按钮', '/cloud/editHadoop.do', '编辑', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2321', '1101', '按钮', '/cloud/deleteHadoop.do', '删除', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2331', '1111', '按钮', '/cloud/saveSpark.do', '新建', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2341', '1111', '按钮', '/cloud/editSpark.do', '编辑', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2351', '1111', '按钮', '/cloud/deleteSpark.do', '删除', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2361', '1121', '按钮', '/cloud/saveEngine.do', '新建', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2371', '1121', '按钮', '/cloud/editEngine.do', '编辑', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2381', '1121', '按钮', '/cloud/deleteEngine.do', '删除', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2391', '921', '按钮', '/db/saveDbConnection.do', '新建', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2401', '921', '按钮', '/db/editDbConnection.do', '编辑', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2411', '921', '按钮', '/db/deleteDbConnection.do', '删除', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2421', '1061', '按钮', '/cloud/saveServer.do', '新建', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2431', '1061', '按钮', '/cloud/editServer.do', '编辑', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2441', '1061', '按钮', '/cloud/deleteServer.do', '删除', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2451', '1071', '按钮', '/cloud/saveCluster.do', '新建', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2461', '1071', '按钮', '/cloud/editCluster.do', '编辑', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2471', '1071', '按钮', '/cloud/deleteCluster.do', '删除', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2481', '1171', '按钮', '/cloud/downloadFile.do', '下载', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2491', '1171', '按钮', '/cloud/deleteFile.do', '删除', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2501', '1221', '按钮', '/cloud/transtype/ClosureGenerator', '闭包生成器', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2502', '731', '菜单', '/EsIndexController/search', 'ES索引', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2503', '2502', '按钮', '/EsIndexController/IndexAndType', '新增', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2504', '2502', '按钮', '/EsIndexController/Modify', '修改', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2505', '2502', '按钮', '/EsIndexController/updateStatus', '修改状态', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2506', '2502', '按钮', '/EsIndexController/history', '历史版本', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2507', '2502', '按钮', '/EsIndexController/switchVersion', '切换版本', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2511', '24', '菜单', '/es/index/list', '全文检索', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2520', '29', '菜单', '/graph/queryRelationship', '数据地图', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2521', '2511', '按钮', '/es/search/custom', '自定义搜索', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2531', '29', '菜单', '/directDataCollect/getdbinfo', '外部数据源采集', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2541', '26', '菜单', '/security/sensitiveInfo/index', '脱敏规则管理', '0', null, '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2551', '1411', '按钮', '/ftpUserPathServiceController/updateStatus', '删除', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2561', '1081', '按钮', '/cloud/jobtype/SqoopImport', 'SqoopImport', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2571', '1081', '按钮', '/cloud/jobtype/SqoopExport', 'SqoopExport', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2581', '1221', '按钮', '/cloud/transtype/HTTP', 'Http客户端', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2591', '1221', '按钮', '/cloud/transtype/HTTPPOST', 'HTTPPOST', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2601', '1221', '按钮', '/cloud/transtype/Rest', 'Rest客户端', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2611', '1221', '按钮', '/cloud/transtype/WebServiceLookup', 'Web服务查询', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2621', '1221', '按钮', '/cloud/transtype/JsonInput', 'Json输入', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2631', '1221', '按钮', '/cloud/transtype/JsonOutput', 'Json输出', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2641', '1221', '按钮', '/cloud/transtype/FuzzyMatch', '模糊匹配', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2651', '1221', '按钮', '/cloud/transtype/DBProc', '调用DB存储过程', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2661', '1221', '按钮', '/cloud/transtype/DynamicSQLRow', '执行Dynamic SQL', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2681', '29', '菜单', '/graph/queryRelationship', '数据地图', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2682', '1221', '按钮', '/cloud/transtype/SetVariable', '设置变量', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2684', '1221', '按钮', '/cloud/transtype/GetVariable', '获取变量', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2691', '1221', '按钮', '/cloud/transtype/DBLookup', '数据库查询', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2701', '1221', '按钮', '/cloud/transtype/FilterRows', '过滤记录', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2731', '1221', '按钮', '/cloud/transtype/Dummy', '空操作', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2741', '1221', '按钮', '/cloud/transtype/RowGenerator', '生成记录', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2751', '1221', '按钮', '/cloud/transtype/MultiwayMergeJoin', '合并加入', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2761', '1221', '按钮', '/cloud/transtype/MergeJoin', '记录集连接', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2771', '1221', '按钮', '/cloud/transtype/SortedMerge', '排序合并', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2781', '1221', '按钮', '/cloud/transtype/GetVariable', '获取变量', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2791', '1221', '按钮', '/cloud/transtype/JoinRows', '记录关联(输出)', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2801', '1221', '按钮', '/cloud/transtype/SystemInfo', '获取系统信息', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2811', '1221', '按钮', '/cloud/transtype/SetVariable', '设置变量', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2812', '28', '菜单', '/resources/database', '系统管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2813', '2812', '菜单', '/resources/database/classify', '资源分类管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2814', '2812', '菜单', '/resources/database/maintenance', '资源维护', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2815', '2812', '菜单', '/resources/database/systemparm', '系统参数', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2816', '2812', '菜单', '/resources/database/service', '服务管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2817', '2816', '菜单', '/resources/database/service/sourceservice', '源服务管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2818', '2816', '菜单', '/resources/database/service/shareservice', '共享服务管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2819', '28', '菜单', '/resources/sourceview', '资源概览', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2820', '28', '菜单', '/resources/management', '资源管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2821', '2820', '菜单', '/resources/management/mysource', '我的资源', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2822', '2820', '菜单', '/resources/management/reporting', '数据上报', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2823', '28', '菜单', '/resources/register', '注册管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2824', '2823', '菜单', '/resources/register/approval', '待我审批', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2825', '2823', '菜单', '/resources/register/approved', '我审批的', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2826', '28', '菜单', '/resources/release', '发布管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2827', '2826', '菜单', '/resources/release/approval', '待我审批', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2828', '2826', '菜单', '/resources/release/approved', '我审批的', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2829', '28', '菜单', '/resources/subscription', '订阅管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2830', '2829', '菜单', '/resources/subscription/mysubscriptions', '我订阅的', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2831', '2829', '菜单', '/subscription/subscription/approval', '待我审批', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2832', '2829', '菜单', '/resources/subscription/approved', '我审批的', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2833', '28', '菜单', '/resources/exchange', '交换管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2834', '2833', '菜单', '/resources/exchange/front', '前置管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2835', '2833', '菜单', '/resources/exchange/serverData', '日志管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2837', '2835', '菜单', '/resources/exchange/serverData/index', '服务日志', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2838', '2833', '菜单', '/resources/exchange/report', '作业管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2839', '2838', '菜单', '/resources/exchange/report/index', '交换作业', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2840', '2838', '菜单', '/resources/exchange/report/exchangeData', '上报作业', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2841', '29', '菜单', '/resources/directory', '数据资源目录', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2842', '2841', '按钮', '/frontMetadataInfoController/searchResource', '数据资源目录搜索结果', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2843', '29', '菜单', '/myResourceController/search', '我的资源', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2844', '29', '菜单', '/myResourceController/getMyApprove', '我的申请', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2845', '29', '菜单', '/resources/unapproved', '待审批', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2846', '29', '菜单', '/resources/approved', '已审批', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2847', '2841', '按钮', '/myResourceController/batchInsert', '申请权限', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2848', '2846', '按钮', '/myResourceController/batchToReCycle', '回收权限', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2851', '2844', '按钮', '/myResourceController/batchToReApprove', '重新申请', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2852', '2844', '按钮', '/myResourceController/batchToRevoke', '撤回申请', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2853', '2845', '按钮', '/myResourceController/batchToPass', '通过', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2854', '2845', '按钮', '/myResourceController/batchToUnPass', '不通过', '1', null, '', 'idatrix-metacube-web');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2856', '1221', '按钮', '/cloud/transtype/ParquetOutput', 'Parquet输出', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2857', '1221', '按钮', '/cloud/transtype/ParquetInput', 'Parquet输入', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2858', '1221', '按钮', '/cloud/transtype/Formula', '公式', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2859', '26', '菜单', '/auditLog/list.shtml', '日志管理', '1', null, '', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2860', '2812', '菜单', '/resources/database/subscription', '订阅关系管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2861', '1221', '按钮', '/cloud/transtype/ReadContentInput', '读取内容', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2864', '2829', '菜单', '/resources/subscription/Relationship', '订阅关系管理', '1', null, '', 'dataResDir');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2865', '1221', '按钮', '/cloud/transtype/CharacterAnalysis', '标准值匹配', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2872', '1221', '按钮', '/cloud/transtype/NumberAnalysis', '电话匹配', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2873', '1221', '按钮', '/cloud/transtype/CertificatesAnalysis', '证件匹配', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2874', '1221', '按钮', '/cloud/transtype/DateAnalysis', '日期匹配', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2875', '1221', '按钮', '/cloud/transtype/CustomAnalysis', '自定义匹配', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2876', '1221', '按钮', '/cloud/transtype/AnalysisReport', '报表生成', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2877', '23', '菜单', '/gather/dataDictionary', '数据字典', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2878', '2877', '按钮', '/analysis/dict.do', '新建', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2879', '2877', '按钮', '/dictDataList/sibmit.do', '编辑', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2880', '2877', '按钮', '/dictDataList/delect.do', '删除', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2881', '2877', '按钮', '/dictDataList/fileUrl.do', '导入', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2882', '2877', '按钮', '/dictDataList/baocun.do', '保存', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2883', '2877', '按钮', '/dictDataList/diceBaocun.do', '字典保存', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2884', '2877', '按钮', '/dictDataList/diceAdd.do', '字典编辑', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2885', '2877', '按钮', '/dictDataList/yes.do', '生效', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2886', '2877', '按钮', '/dictDataList/No.do', '未生效', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2887', '2877', '按钮', '/dictDataList/inst.do', '待更新', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2888', '1221', '按钮', '/cloud/transtype/RegexEval', '正则表达式', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2889', '1221', '按钮', '/cloud/transtype/ExcelOutput', 'Excel输出', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2890', '1221', '按钮', '/cloud/transtype/KafkaConsumerInput', 'kafka消费者', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2891', '1221', '按钮', '/cloud/transtype/KafkaProducerOutput', 'kafka生产者', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2892', '1221', '按钮', '/cloud/transtype/RecordsFromStream', '结果中的流', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2893', '8', '按钮', '/member/user/all.shtml', '获取所有用户信息', '1', null, '提供给bbs用户同步使用', 'security');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2905', '24', '菜单', '/analysis/ReportForms', 'BI分析', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2906', '2905', '菜单', '/analysis/DataModel', '数据模型', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2907', '2905', '菜单', '/analysis/ReportForms/New', '新建报表分析', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2908', '2905', '菜单', '/analysis/ReportForms/Open', '打开报表分析', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2909', '23', '菜单', '/gather/qualityAnalysis/taskList', '质量分析', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2910', '2909', '菜单', '/gather/qualityAnalysis/designSpace', '分析任务', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2911', '2909', '菜单', '/gather/qualityAnalysis/report', '分析列表', '1', null, '', 'cloudetl');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2912', '2906', '按钮', '/saiku/rest/schema/insertSchema', '新建模型', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2913', '2906', '按钮', '/saiku/rest/schema/batchDelete', '删除模型', '1', null, '', 'datalab');
INSERT INTO `idatrix_unisecurity_permission` VALUES ('2914', '2906', '按钮', '/saiku/rest/schema/importToSaiku', '一键导入模型', '1', null, '', 'datalab');





-- 角色权限关联
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '3', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '4', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '5', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '6', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '7', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '8', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '12', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '14', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '16', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '17', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '18', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '20', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '21', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '22', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '23', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '24', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '25', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '26', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '27', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '28', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '29', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '30', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '32', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '33', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '34', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '35', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '37', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '40', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '42', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '43', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '44', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '45', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '46', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '61', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '71', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '81', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '91', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '101', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '171', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '181', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '191', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '201', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '211', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '221', '2017-08-22 16:48:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '361', '2017-08-28 09:42:33');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '371', '2017-08-30 09:44:30');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '381', '2017-08-31 09:39:48');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '401', '2017-08-31 09:40:44');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '411', '2017-08-31 09:41:12');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '421', '2017-08-31 09:42:00');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '431', '2017-08-31 09:42:19');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '441', '2017-08-31 09:42:37');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '451', '2017-08-31 09:43:08');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '461', '2017-08-31 09:43:30');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '501', '2017-09-04 11:54:05');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '511', '2017-09-04 11:54:16');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '521', '2017-09-04 11:54:28');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '531', '2017-09-04 11:54:38');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '541', '2017-09-04 11:54:49');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '551', '2017-09-04 11:54:59');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '561', '2017-09-04 11:55:11');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '571', '2017-09-04 11:55:25');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '581', '2017-09-04 11:55:38');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '591', '2017-09-04 11:55:49');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '601', '2017-09-04 14:54:27');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '611', '2017-09-04 14:54:57');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '621', '2017-09-04 14:55:12');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '631', '2017-09-04 14:55:31');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '641', '2017-09-04 14:55:44');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '651', '2017-09-04 14:55:54');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '661', '2017-09-04 15:22:06');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '671', '2017-09-04 15:22:18');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '681', '2017-09-04 15:22:28');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '691', '2017-09-04 15:22:38');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '701', '2017-09-04 15:24:33');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '711', '2017-09-04 15:27:59');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '721', '2017-09-04 15:28:09');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '731', '2017-09-04 15:28:19');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '741', '2017-09-04 15:28:29');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '751', '2017-09-04 15:28:41');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '901', '2017-09-14 17:00:18');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '911', '2017-09-14 17:00:46');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '921', '2017-09-14 17:08:53');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1001', '2017-09-14 17:29:15');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1031', '2017-09-14 17:31:51');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1041', '2017-09-14 17:33:30');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1051', '2017-09-14 17:34:12');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1061', '2017-09-14 17:39:51');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1071', '2017-09-14 17:40:16');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1081', '2017-09-14 17:44:30');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1091', '2017-09-14 17:48:02');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1101', '2017-09-14 17:49:15');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1111', '2017-09-14 17:50:00');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1121', '2017-09-14 17:50:26');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1131', '2017-09-14 17:50:28');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1141', '2017-09-14 17:53:40');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1151', '2017-09-14 17:54:18');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1161', '2017-09-14 17:54:59');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1171', '2017-09-14 17:55:33');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1181', '2017-09-14 17:57:43');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1191', '2017-09-14 17:58:19');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1201', '2017-09-14 17:59:10');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1211', '2017-09-14 17:59:50');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1221', '2017-09-14 18:00:02');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1231', '2017-09-14 18:02:08');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1241', '2017-09-14 18:03:17');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1251', '2017-09-14 18:03:57');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1261', '2017-09-14 18:04:41');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1271', '2017-09-14 18:06:24');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1281', '2017-09-14 18:07:38');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1301', '2017-09-14 18:09:07');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1311', '2017-09-14 18:11:56');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1321', '2017-09-14 18:12:32');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1331', '2017-09-14 18:13:00');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1341', '2017-09-14 18:17:26');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1351', '2017-09-15 09:24:26');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1361', '2017-09-15 09:24:44');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1371', '2017-09-15 09:24:58');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1401', '2017-09-15 09:28:29');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1411', '2017-09-15 09:29:12');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1421', '2017-09-15 09:29:31');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1431', '2017-09-15 09:29:53');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1441', '2017-09-15 09:33:15');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1451', '2017-09-15 09:35:40');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1461', '2017-09-15 09:36:22');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1471', '2017-09-15 09:36:58');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1481', '2017-09-15 09:37:20');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1491', '2017-09-15 09:37:28');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1501', '2017-09-15 09:38:01');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1511', '2017-09-15 09:38:16');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1521', '2017-09-15 09:38:44');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1531', '2017-09-15 09:39:10');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1541', '2017-09-15 09:39:46');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1551', '2017-09-15 09:40:20');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1561', '2017-09-15 09:40:42');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1571', '2017-09-15 09:41:22');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1581', '2017-09-15 09:42:06');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1591', '2017-09-15 09:47:14');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1601', '2017-09-15 09:47:56');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1611', '2017-09-15 09:48:18');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1621', '2017-09-15 09:48:44');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1631', '2017-09-15 09:49:12');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1641', '2017-09-15 09:49:52');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1651', '2017-09-15 09:49:59');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1661', '2017-09-15 09:50:29');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1671', '2017-09-15 09:50:48');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1681', '2017-09-15 09:50:59');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1691', '2017-09-15 09:51:21');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1701', '2017-09-15 09:51:33');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1711', '2017-09-15 09:53:07');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1721', '2017-09-15 09:53:46');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1731', '2017-09-15 09:55:51');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1741', '2017-09-15 09:56:21');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1751', '2017-09-15 09:56:47');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1761', '2017-09-15 09:57:26');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1771', '2017-09-15 09:57:52');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1781', '2017-09-15 09:58:25');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1791', '2017-09-15 09:58:52');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1801', '2017-09-15 09:59:17');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1811', '2017-09-15 09:59:52');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1821', '2017-09-15 10:00:29');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1831', '2017-09-15 10:01:01');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1841', '2017-09-15 10:01:10');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1851', '2017-09-15 10:01:34');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1861', '2017-09-15 10:01:59');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1871', '2017-09-15 10:02:11');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1881', '2017-09-15 10:02:32');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1891', '2017-09-15 10:02:53');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1901', '2017-09-15 10:02:55');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1911', '2017-09-15 10:03:20');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1921', '2017-09-15 10:03:50');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1931', '2017-09-15 10:04:21');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1941', '2017-09-15 10:05:00');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1951', '2017-09-15 10:07:38');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1961', '2017-09-15 10:09:57');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1971', '2017-09-15 10:20:39');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1981', '2017-09-15 10:21:28');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '1991', '2017-09-15 10:25:12');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2031', '2017-09-15 10:34:29');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2041', '2017-09-15 10:34:46');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2051', '2017-09-15 10:35:00');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2061', '2017-09-15 11:22:54');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2071', '2017-09-15 11:24:09');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2081', '2017-09-15 11:58:52');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2091', '2017-09-15 14:03:41');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2101', '2017-09-15 14:04:15');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2111', '2017-09-15 14:05:26');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2121', '2017-09-15 14:07:27');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2131', '2017-09-15 18:47:05');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2141', '2017-09-15 18:47:27');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2151', '2017-09-15 18:51:32');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2161', '2017-09-15 18:53:34');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2171', '2017-09-15 18:54:32');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2181', '2017-09-15 19:01:55');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2191', '2017-09-15 19:05:05');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2201', '2017-09-15 19:06:52');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2281', '2017-09-16 14:06:33');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2291', '2017-09-16 14:06:43');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2301', '2017-09-18 09:49:09');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2311', '2017-09-18 09:49:28');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2321', '2017-09-18 09:49:52');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2331', '2017-09-18 09:50:21');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2341', '2017-09-18 09:50:44');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2351', '2017-09-18 09:51:28');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2361', '2017-09-18 09:51:59');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2371', '2017-09-18 09:52:16');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2381', '2017-09-18 09:52:35');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2391', '2017-09-18 09:54:34');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2401', '2017-09-18 09:54:58');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2411', '2017-09-18 09:55:16');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2421', '2017-09-18 09:55:40');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2431', '2017-09-18 09:56:00');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2441', '2017-09-18 09:56:16');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2451', '2017-09-18 09:56:47');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2461', '2017-09-18 09:57:04');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2471', '2017-09-18 09:57:25');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2481', '2017-09-18 13:55:25');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2491', '2017-09-18 13:56:27');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2501', '2017-09-20 11:47:41');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2682', '2018-07-16 17:13:47');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2684', '2018-07-22 16:05:08');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2812', '2018-08-10 10:58:05');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2813', '2018-08-10 10:58:43');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2814', '2018-08-10 10:59:00');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2815', '2018-08-10 10:59:14');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2816', '2018-08-10 10:59:27');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2817', '2018-08-10 10:59:42');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2818', '2018-08-10 10:59:56');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2819', '2018-08-10 11:00:15');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2820', '2018-08-10 11:00:48');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2821', '2018-08-10 11:01:07');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2822', '2018-08-10 11:01:25');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2823', '2018-08-10 11:02:23');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2824', '2018-08-10 11:02:37');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2825', '2018-08-10 11:02:51');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2826', '2018-08-10 11:03:15');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2827', '2018-08-10 11:03:39');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2828', '2018-08-10 11:03:51');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2829', '2018-08-10 11:04:08');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2830', '2018-08-10 11:04:27');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2831', '2018-08-10 11:04:54');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2832', '2018-08-10 11:05:09');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2833', '2018-08-10 11:06:01');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2834', '2018-08-10 11:06:17');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2835', '2018-08-10 11:06:29');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2837', '2018-08-10 11:07:06');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2838', '2018-08-10 11:07:25');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2839', '2018-08-10 11:07:44');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2840', '2018-08-10 11:08:02');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2841', '2018-08-11 11:43:13');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2842', '2018-08-11 11:43:44');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2843', '2018-08-11 11:44:47');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2844', '2018-08-11 11:45:06');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2845', '2018-08-11 11:45:30');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2846', '2018-08-11 11:45:48');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2847', '2018-08-11 11:58:15');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2848', '2018-08-11 11:59:54');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2851', '2018-08-11 12:01:29');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2852', '2018-08-11 12:01:47');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2853', '2018-08-11 12:02:31');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2854', '2018-08-11 12:04:17');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2855', '2018-08-20 11:54:10');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2856', '2018-08-23 10:46:04');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2857', '2018-08-23 10:46:28');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2858', '2018-08-23 10:46:53');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2859', '2018-08-29 19:25:59');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2860', '2018-08-31 10:43:51');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2861', '2018-09-17 14:19:54');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2864', '2018-09-25 18:39:26');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2865', '2018-10-18 09:51:19');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2872', '2018-10-18 09:55:09');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2873', '2018-10-18 09:55:24');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2874', '2018-10-18 09:55:58');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2875', '2018-10-18 09:56:24');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2876', '2018-10-18 09:56:58');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2877', '2018-10-26 18:45:27');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2878', '2018-10-30 15:44:47');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2879', '2018-10-30 15:52:27');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2880', '2018-11-02 14:44:33');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2881', '2018-11-02 14:45:39');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2882', '2018-11-02 14:46:18');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2883', '2018-11-02 14:54:41');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2884', '2018-11-02 14:55:47');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2885', '2018-11-02 17:27:24');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2886', '2018-11-02 17:27:39');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2887', '2018-11-02 17:28:04');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2888', '2018-11-08 10:08:51');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2889', '2018-11-08 10:09:08');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2890', '2018-11-08 10:09:28');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2891', '2018-11-08 10:10:26');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2892', '2018-11-08 10:10:42');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2893', '2018-11-09 11:24:05');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2902', '2018-11-14 15:18:08');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2903', '2018-11-14 15:28:56');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2904', '2018-11-14 15:56:00');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2905', '2018-11-21 15:47:44');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2906', '2018-11-21 15:48:22');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2907', '2018-11-21 15:48:44');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2908', '2018-11-21 15:49:04');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2909', '2018-11-21 17:47:33');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2910', '2018-11-21 17:48:08');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2911', '2018-11-21 17:48:27');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2912', '2018-11-29 11:22:43');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2913', '2018-11-29 11:35:16');
INSERT INTO `idatrix_unisecurity`.`idatrix_unisecurity_role_permission` (`rid`, `pid`, `create_time`) VALUES ('1', '2914', '2018-11-29 11:36:26');






